
services:
  backend:
    container_name: sig_one_backend
    restart: unless-stopped
    image: sig-one-backend:1.0.0
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - CLIENT_ID=${CLIENT_ID}
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - shared-network
  
  frontend:
    container_name: sig_one_frontend
    restart: unless-stopped
    image: sig-one-frontend:1.0.0
    environment:
      - REACT_APP_CLIENT_ID=${REACT_APP_CLIENT_ID}
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - shared-network
    depends_on:
      - backend

networks:
  shared-network: